/* One schema owns JSON validation and accessible viewer controls. */
(function () {
  'use strict';
  const fields=[];
  const number=(group,path,label,min,max,step=.01)=>fields.push({group,path,label,min,max,step,type:'number'});
  const check=(group,path,label)=>fields.push({group,path,label,type:'checkbox'});
  const choice=(group,path,label,values)=>fields.push({group,path,label,values,type:'select'});
  choice('View','renderer','Renderer',['neon','original']);
  choice('View','quality','Quality',['fast','medium','high']);
  number('View','n_steps','Raytrace steps',20,300,1);
  number('View','time_scale','Time scale',0,8);
  check('Orbit','observer.motion','Automatic orbit');
  choice('Orbit','observer.orbit','Orbit',['eccentric','circular']);
  number('Orbit','observer.periapsis','Periapsis (rₛ)',3.2,30);
  number('Orbit','observer.apoapsis','Apoapsis (rₛ)',3.2,60);
  number('Camera','observer.distance','Camera radius (rₛ)',3.01,30);
  number('Orbit','observer.orbital_inclination','Inclination (°)',-90,90);
  number('Camera','observer.azimuth','Stationary position azimuth (°)',-180,180);
  number('Camera','observer.elevation','Stationary position elevation (°)',-85,85);
  number('Camera','camera.height','Stationary camera height offset (rₛ)',-100,100,.01);
  number('Camera','observer.rotation_speed','Stationary camera rotation (°/s)',-30,30);
  choice('Camera','camera.navigation','Move control',['orbit','free']);
  number('Camera','camera.sensitivity','Look / move sensitivity',.01,1,.01);
  number('Camera','camera.move_speed','Movement speed (rₛ/s)',.01,10,.01);
  for(const axis of ['x','y','z']) number('Camera','camera.offset_'+axis,'Camera offset '+axis.toUpperCase()+' (rₛ)',-100,100,.01);
  number('Camera','camera.pitch','Pitch (°)',-60,60);
  number('Camera','camera.yaw','Yaw (°)',-180,180);
  number('Camera','camera.wobble_pitch','Pitch wobble (°)',0,20);
  number('Camera','camera.wobble_yaw','Yaw wobble (°)',0,30);
  number('Camera','camera.wobble_period','Wobble period (s)',4,120);
  for(const [key,label] of [['photon_eq_fix','Correct photon equation'],['neon_floor','Grid floor'],['neon_sky','Nebula sky'],['neon_grid','Sky grid'],['disk_flow','Disk turbulence'],['disk_profile','Disk temperature profile'],['grav_redshift','Gravitational redshift']]) check('Neon features',key,label);
  check('Floor','look.floor_follow_camera','Floor follows camera');
  check('Floor','look.floor_lensing','Lens the floor around the black hole');
  for(const [key,label,min,max] of [['floor_strength','Brightness',0,3],['floor_height','Black hole height above floor (rₛ)',-50,100],['floor_x','Floor X offset (rₛ)',-100,100],['floor_y','Floor Y offset (rₛ)',-100,100],['floor_yaw','Floor heading (°)',-180,180],['floor_tilt','Tilt (°)',-80,80],['floor_cell','Cell size (rₛ)',.5,20],['floor_speed','Forward drift',-2,2],['floor_sway','Sideways sway (rₛ)',0,20],['floor_sway_period','Sway period (s)',4,120],['floor_extent','Extent',2,100]]) number('Floor','look.'+key,label,min,max);
  check('Disk','accretion_disk','Accretion disk');
  number('Disk','look.disk_tilt','Disk tilt (°)',-90,90);
  number('Disk','look.disk_yaw','Disk tilt direction (°)',-180,180);
  check('Floor','look.floor_infinite','Infinite floor / horizon');
  number('Floor','look.floor_concentration','Distant wire concentration',0,40);
  check('Floor','look.floor_palette','Custom grid colors');
  fields.push({group:'Floor',path:'look.floor_color',label:'Grid color',type:'color'});
  fields.push({group:'Floor',path:'look.floor_major_color',label:'Major grid color',type:'color'});
  number('Floor','look.floor_reflection','Floor reflectivity (extra render pass)',0,1);
  number('Floor','look.floor_roughness','Reflection roughness',0,1);
  number('Disk','look.gas_tint','Gas color blend',0,1);
  fields.push({group:'Disk',path:'look.gas_color',label:'Gas color',type:'color'});
  fields.push({group:'Disk',path:'look.gas_texture',label:'Gas texture',type:'texture'});
  check('Poster text','caption.enabled','Show poster text');
  check('Poster text','caption.uppercase','Uppercase lettering');
  number('Poster text','caption.bevel','Metal bevel',0,2);
  number('Poster text','caption.grid','Reflected grid detail',0,1);
  fields.push({group:'Poster text',path:'caption.text',label:'Text (use | for a new line)',type:'text',maxLength:120});
  choice('Poster text','caption.style','Finish',['chrome','iridescent','mixed']);
  choice('Poster text','caption.font','Lettering',['block','Orbitron','Teko']);
  number('Poster text','caption.size','Letter height (% of view)',2,25);
  number('Poster text','caption.x','Horizontal center (%)',0,100);
  number('Poster text','caption.y','Vertical center (%)',0,100);
  number('Poster text','caption.width','Maximum text width (%)',10,100);
  number('Poster text','caption.stretch','Letter width multiplier',.5,2);
  number('Poster text','caption.line_gap','Line spacing multiplier',.8,1.5);
  number('Disk','look.disk_temp','Peak temperature (K)',2000,20000,1);
  number('Disk','look.disk_outer','Outer radius (rₛ)',3,30);
  number('Disk','look.disk_speed','Gas speed (1 = Keplerian)',0,10);
  number('Disk','look.spot_strength','Hot spots',0,4);
  check('Sky','look.sky_motion','Move stars / galaxies');
  number('Sky','look.sky_speed','Sky speed (°/s; negative reverses)',-30,30,.01);
  number('Sky','look.sky_axis_tilt','Sky rotation axis tilt (°)',-90,90);
  number('Sky','look.nebula_amount','Extra gas clouds',0,3);
  number('Sky','look.nebula_scale','Gas cloud detail',1,8);
  fields.push({group:'Sky',path:'look.nebula_color',label:'Gas cloud color',type:'color'});
  for(const [key,label,min,max] of [['galaxy_gain','Galaxy brightness',0,6],['grid_strength','Grid brightness',0,3],['grid_glow','Grid glow (px)',0,12],['grid_pulse','Grid pulse',0,3],['vfov','Maximum vertical FOV (°)',30,120]]) number('Sky','look.'+key,label,min,max);
  for(const [key,label,min,max] of [['exposure','Exposure',.2,4],['bloom_strength','Bloom strength',0,3],['bloom_threshold','Bloom threshold',0,1.5],['bloom_radius','Bloom radius',.25,4],['render_scale','Maximum render scale',.25,1]]) number('Post / performance','look.'+key,label,min,max);
  check('Post / performance','look.auto_res','Automatic resolution');
  check('Post / performance','look.antialiasing','Antialiasing (FXAA)');
  number('Post / performance','look.target_fps','Target FPS',24,120,1);
  for(const [key,label] of [['beaming','Relativistic beaming'],['doppler_shift','Doppler shift'],['aberration','Aberration'],['light_travel_time','Light travel time'],['gravitational_time_dilation','Time dilation'],['lorentz_contraction','Lorentz contraction']]) check('Physics',key,label);
  check('Planet','planet.enabled','Planet');
  number('Planet','planet.distance','Semi-major axis (rₛ)',3,30);
  number('Planet','planet.radius','Radius (rₛ)',.01,2);
  number('Planet','planet.eccentricity','Orbital eccentricity',0,.8,.01);
  number('Planet','planet.inclination','Orbital inclination (°)',-180,180);
  number('Planet','planet.node','Ascending node (°)',-180,180);
  number('Planet','planet.periapsis','Periapsis direction (°)',-180,180);
  number('Planet','planet.phase','Initial orbital phase (°)',-180,180);
  number('Planet','planet.speed','Orbital speed multiplier',0,2,.01);
  number('Planet','planet.spin','Surface spin (°/s)',-90,90);
  number('Planet','planet.axial_tilt','Axial tilt (°)',-180,180);
  number('Planet','planet.texture_offset','Texture longitude offset',0,1,.001);
  fields.push({group:'Planet',path:'planet.texture',label:'Planet texture',type:'texture'});
  const get=(obj,path)=>path.split('.').reduce((v,k)=>v?.[k],obj);
  function set(obj,path,value){const keys=path.split('.'),key=keys.pop();keys.reduce((v,k)=>v[k],obj)[key]=value;}
  function validate(input,defaults){
    if(!input||typeof input!=='object'||Array.isArray(input)) throw new Error('Settings must be a JSON object.');
    if(input.version!==undefined&&input.version!==1) throw new Error('Unsupported settings version.');
    const output=JSON.parse(JSON.stringify(defaults));
    const allowed=new Set(['version','t','r','v','render_scale_now',...fields.map(f=>f.path.split('.')[0])]);
    for(const key of Object.keys(input)) if(!allowed.has(key)) throw new Error('Unknown setting: '+key);
    for(const group of ['camera','observer','look','planet','caption']){
      if(!Object.hasOwn(input,group)) continue;
      if(!input[group]||typeof input[group]!=='object'||Array.isArray(input[group])) throw new Error(group+' must be an object.');
      const keys=new Set(fields.filter(f=>f.path.startsWith(group+'.')).map(f=>f.path.split('.')[1]));
      for(const key of Object.keys(input[group])) if(!keys.has(key)) throw new Error('Unknown setting: '+group+'.'+key);
    }
    for(const field of fields){
      const value=get(input,field.path);
      if(value===undefined) continue;
      if(field.type==='checkbox'&&typeof value!=='boolean') throw new Error(field.label+' must be true or false.');
      if(field.type==='select'&&!field.values.includes(value)) throw new Error('Invalid '+field.label.toLowerCase()+'.');
      if(field.type==='number'&&(typeof value!=='number'||!Number.isFinite(value)||value<field.min||value>field.max||field.step===1&&!Number.isInteger(value))) throw new Error(field.label+' must be between '+field.min+' and '+field.max+'.');
      if(field.type==='texture'&&(typeof value!=='string'||value.length>3000000||(value!==''&&!/^data:image\/(png|jpeg|webp);base64,[A-Za-z0-9+/]+={0,2}$/.test(value)))) throw new Error(field.label+' must be an embedded PNG, JPEG or WebP under 3 MB.');
      if(field.type==='color'&&(typeof value!=='string'||!/^#[0-9a-f]{6}$/i.test(value))) throw new Error(field.label+' must be a six-digit hex color.');
      if(field.type==='text'&&(typeof value!=='string'||value.length>field.maxLength)) throw new Error(field.label+' must be at most '+field.maxLength+' characters.');
      set(output,field.path,value);
    }
    const o=output.observer;
    if(o.orbit==='eccentric'&&(o.apoapsis<o.periapsis||1-1/o.periapsis-1/o.apoapsis<1/o.periapsis-1e-9)) throw new Error('Choose a bound orbit: increase periapsis or apoapsis.');
    if(!o.motion){const a=o.azimuth*Math.PI/180,e=o.elevation*Math.PI/180,c=output.camera;if(Math.hypot(o.distance*Math.cos(a)*Math.cos(e)+c.offset_x,o.distance*Math.sin(a)*Math.cos(e)+c.offset_y,o.distance*Math.sin(e)+c.height+c.offset_z)<1.5)throw new Error('Keep the camera outside 1.5 rₛ.');}
    if(output.planet.distance*(1-output.planet.eccentricity)<=output.planet.radius+1.5) throw new Error('Planet periapsis must keep the whole planet outside 1.5 rₛ. Increase orbital distance or reduce eccentricity.');
    output.version=1;
    return output;
  }
  window.NeonSettings={fields,get,set,validate};
})();
